"""add password reset token

Revision ID: 8d9773c7ee8e
Revises: df32ac357388
Create Date: 2026-01-30 23:00:08.216963

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d9773c7ee8e'
down_revision = 'df32ac357388'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.alter_column('actor_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('org_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('action',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.drop_constraint(batch_op.f('audit_log_user_id_fkey'), type_='foreignkey')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reset_token', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('reset_token_expires_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_user_reset_token'), ['reset_token'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_reset_token'))
        batch_op.drop_column('reset_token_expires_at')
        batch_op.drop_column('reset_token')

    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('audit_log_user_id_fkey'), 'user', ['actor_id'], ['id'])
        batch_op.alter_column('action',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)
        batch_op.alter_column('org_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('actor_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
